version: '3.8'
services:
  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./SPA
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - backend
